catalog/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from .views import *
from rest_framework import routers


routers=routers.DefaultRouter()
routers.register('detail_book/',views.bookdetail)
urlpatterns=[
    path('',include(routers.urls)),
    path('index/',views.index),
    path('create_book/',views.Bookcreate.as_view(),name='create_book'),
    path('book_detail/<int:pk>/',views.book_detail.as_view(),name='book_detail'),
    path('signup/',views.sign_up.as_view(),name='sign_up'),
    path('profile/',views.checkedbyuser.as_view(),name='profile')



]

my_app/urls.py
from django.urls import path
from . import views
app_name='my_app'
urlpatterns = [
    path('home/', views.index,name='variable'),
    path('variable/',views.variable,name='variables'),
    path('<int:num1>/<int:num2>', views.add),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('office/', include('office.urls')),
    path('classroom/',include('classroom.urls')),
    path('catalog/', include('catalog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class genr(models.Model):
    name=models.CharField(max_length=100)
    def __str__(self):
        return f"{self.name}"

class language(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

class auther(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    date_of_birth=models.DateField(null=True,blank=True)

    class Meta:
        ordering=['last_name','first_name']
    def __str__ (self):
        return f"{self.first_name} {self.last_name}"   


    def get_absolute_url(self):
        return reverse('auther_detail',kwargs={'pk':self.pk })    

class book(models.Model):
    title=models.CharField(max_length=100)
    auther=models.ForeignKey(auther,on_delete=models.SET_NULL,null=True) 
    summary=models.TextField(max_length=50,unique=True)   
    isbn=models.CharField('ISBN',max_length=13)
    language=models.ForeignKey(language,on_delete=models.SET_NULL,null=True)

    genre=models.ManyToManyField(genr)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return  reverse('book_detail',kwargs={'pk':self.pk})
import uuid

class BookInstance(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4)
    book=models.ForeignKey(book,on_delete=models.RESTRICT,null=True)
    imprint=models.CharField(max_length=200)
    due_back=models.DateField(null=True,blank=True)
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

    LOAN_STATUS=(
        ('m','Maintenance'),
        ('o','On Loan'),
        ('a','available'),
        ('r','reversed')
    )
    status=models.CharField(max_length=100,choices=LOAN_STATUS,blank=True,default='m')

    class  META:
        ordering=['due_back']
    
    def  __str__(self):
        return f'{self.id}({self.book.title})'

catalog/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import CreateView,DetailView,ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from .serializers import *
from rest_framework import viewsets



# Create your views here.

def index(request):
    num_book=book.objects.all().count()
    num_instance=BookInstance.objects.all().count()
    num_instance_avail=BookInstance.objects.filter(status__exact='a').count()
    context={
        'num_book':num_book,
        'num_instance':num_instance,
        'num_instance_avail':num_instance_avail
    }
    return render(request,'catalog_app/index.html',context=context)

class Bookcreate(LoginRequiredMixin,CreateView):
    model=book
    template_name="catalog_app/book_form.html"
    # success_url='catalog_app/book_detail/'
    fields='__all__'

# @login_required       
class book_detail(DetailView):
    model=book
    template_name="catalog_app/book_detail.html"

class sign_up(CreateView):
    form_class =UserCreationForm
    template_name='catalog_app/sign_up.html'
    success_url='/accounts/login/'


class checkedbyuser(LoginRequiredMixin,ListView):
    model=BookInstance  
    template_name='catalog_app/profile.html'
    paginate_by=5
    def get_query(self):
        return BookInstance.objects.filter(borrower=self.request.user)
     
        


class bookdetail(viewsets.ModelViewSet):

    queryset=book.objects.all()
    serializer_class=book_serializer

catalog/templates/catalog_app/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{book}}
</body>
</html>

catalog/templates/catalog_app/book_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input  type="submit">
</form>
</body>
</html>

catalog/templates/catalog_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  {%if user.is_authenticated%}
  <h1>welcome : {{user.get_username}} </h1><a href="{% url 'logout'%}?next={{request.path}}">click to logout </a>
  <p>you are logged In </p>
  Num of books : {{num_book}}
  AVAILABLE : {{num_instance_avail}}
  {%else%}
  <p>you are loggged out</p><a href="{%url 'login'%}?next={{request.path}}">click to login</a>
  Num of books : {{num_book}}
  AVAILABLE : {{num_instance_avail}}
  
  
  {%endif%}
</body>
</html>

catalog/templates/catalog_app/profile.html
<h1>welcome to your profile</h1>
<p>here your books checked out</p>
{%for book in bookinstance_list %}
{{book}}
{%endfor%}

catalog/templates/catalog_app/sign_up.html
<h1>Sign up form</h1>
<form action="" method="post" >
{%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="signup">
</form>