my_app/urls.py
from django.urls import path
from . import views
app_name='my_app'
urlpatterns = [
    path('home/', views.index,name='variable'),
    path('variable/',views.variable,name='variables'),
    path('<int:num1>/<int:num2>', views.add),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('office/', include('office.urls')),
    path('classroom/',include('classroom.urls')),
    path('catalog/', include('catalog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

my_app/models.py
from django.db import models

# class patient(models.Model):
#     first_name=models.CharField(max_length=100)
#     last_name=models.CharField(max_length=100)
#     age=models.IntegerField()

my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    variable={
        'name':'abdulRaza',
        'city':'kota rajasthan',
        'user_logged_in':False
    }
    return render(request,'first_app/example.html',variable)
def variable(request):
    variable={
        'name':'abdulRaza',
        'city':'kota rajasthan',
    }
    return render(request,'first_app/variable.html',variable)
def add(request,num1,num2):
    result=num1+num2
    return HttpResponse(f"{num1} and {num2}=={result}")

my_app/templates/first_app/example.html
{% extends "base.html" %}   
{% load static %}
    {% block body%}
    {% comment %} <h1>hello there</h5>
        <h2>{{name|lower|capfirst}}</h2>
        <h2>{{city.0}}</h2>
    {%if user_logged_in%}
    <h1>welcom you are loggedin</h1>
    {%endif%} {% endcomment %}
    <p><a href="{%url 'my_app:variables'%}">click me </a></p>
    <img src="{% static 'first_app/django-logo-negative.png' %}">
{%endblock body%}

my_app/templates/first_app/variable.html
{%extends 'base.html'%}
{%block body%}

    <h1>welcome to variable page</h1>
   
{%endblock%}